### ISSUE TITLE
Multiple soyToImport configs

### ISSUE THREAD

**Issue by jbalsas** [metal/metal-soy-critic#13]
Currently, we support just one pair

```
  "callToImportRegex": "(\\S+)",
  "callToImportReplace": "{$1|param}"
```

This can be problematic if different types of imports are mixed in the same project, making it really hard to adapt. We could try to

Have synced arrays

```json
callToImportRegex: string|array<string>
callToImportReplace: string|array<string>
```

Or move this directly to an array of regex,replace pairs

```json
callToImport: [
    {
        regex: /regex1/,
        replace: 'replace1'
    }, {
        regex: /regex2/,
        replace: 'replace2'
    }
]
```

I'm not sure if anyone other than us is using the old syntax. The new one feels more robust. We could try to deprecate the old one, or just break it and release a major change if we don't care about maintaining that.

Thoughts, @Robert-Frampton, @mthadley?

**Comment by Robert-Frampton** [comment]
Seems fine to just update the API and do a major release.

It would also be really easy to just map `callToImportRegex` and `callToImportReplace` to the new API if they are found in a `.soycriticrc.json` file, and maybe print a warning to update it.

**Comment by mthadley** [comment]
@Robert-Frampton Yup, totally agree. It should be an easy addition. 💯
