### ISSUE TITLE
These params can't be found in STATE or your Class:

### ISSUE THREAD

**Issue by Robert-Frampton** [metal/metal-soy-critic#5]
If I have class A, that extends class B, and the soy template for A implements STATE params from B it will show the following error.

```
These params can't be found in STATE or your Class:
```

The parent class needs to be resolved and parsed as well. Obviously that makes things a lot more complicated :)

**Comment by mthadley** [comment]
My immediate thought is that we could just skip validation for classes that do not extend directly from `Component`, since we can't be sure what the developer is doing. In the future, it would be nice if we could do all those things you mentioned, though.

**Comment by mthadley** [comment]
So with c362df8539896efd8ebd6a35d1e35040ea6c2c2c,  we will just skip those files for now until we can find a better solution.

**Comment by jbalsas** [comment]
After https://github.com/mthadley/metal-soy-critic/issues/9, I also got hit by this now...

```
File - packages/clay-link/src/ClayLink.soy

     These params can't be found in STATE or your Class:
     
     elementClasses
```

Also, is there a typo in the message, where it should say _STATE **of** your Class_?

We can't ignore all the files, though 😂 

Now that we have `.mcriticsrc`, maybe we could have something like this?

```
{
    "classParams": {
        "Component": ["elementClasses", "visible"]
    }
}
```

**Comment by mthadley** [comment]
It's actually just a bad message on my part. I'm trying to say it can't be found in STATE or as a method of your class. I need a wordsmith here, quick! 😄 

Yea, I'm open to something like that. A default set of STATE attributes.

**Comment by jbalsas** [comment]
My first instinct was to go with some `globals` à la `eslint`

```javascript
{
    "globalParams": ["elementClasses", "visible"]
}
```

That would of course be easier to implement but also more prone to error since it disregards the inheritance chain completely. Maybe something like:

```javascript
{
    "implicitParams": {
        "Clay*": ["elementClasses", "visible"],
        "OtherTemplate": ["foo", "bar"]
    }
}
```

What do you think?

**Comment by mthadley** [comment]
@jbalsas I really like this idea. Let's go with it.

**Comment by mthadley** [comment]
@jbalsas @Robert-Frampton Are there any use cases not covered by the new `implicitParams` configuration? Can this be closed now?

**Comment by jbalsas** [comment]
Based on https://github.com/metal/metal-clay-components/pull/65 it looks like we can... ☺️
