### ISSUE TITLE
Allow for use as a Library.

### ISSUE THREAD

**Issue by mthadley** [metal/metal-soy-critic#7]
We should export some functions that allows using `metal-soy-critic` as a library. We will probably need to update some of the return types so that they make sense for more generic use cases.

We can also consider adding a JSON output option. This would be useful for integration with tools like linters, continuous integration, etc.

**Comment by jbalsas** [comment]
This is the pre-requisite for integration into https://github.com/liferay/liferay-frontend-source-formatter/issues/21

**Comment by jbalsas** [comment]
Filed at [metal-tools-soy](https://github.com/metal/metal-tools-soy/issues/40)
